Revert "Revert "Fix 388""
celements/celements-blog pull request #21
Opened 2017-01-31 14:31 UTC by nderguti

Reverts celements/celements-blog#20

2017-01-31 15:24 UTC, msladek requested changes
project has compile errors, please finish changes first before requesting reviews.

i think these errors came in due to a bad merge with the dev

2017-01-31 17:51 UTC, msladek requested changes

2017-01-31 17:51 UTC, msladek commented on component/pom.xml
> +      <version>1.160</version>
update to current version 1.162

2017-01-31 17:51 UTC, msladek commented on component/src/main/java/com/celements/blog/plugin/NewsletterReceivers.java
> +        LOGGER.error("UTF-8 unsupported.");
give exception a better name and add it to error logging

2017-01-31 17:51 UTC, msladek commented on component/src/test/java/com/celements/blog/plugin/NewsletterReceiversTest.java
> +  public void unsubscribeLink(String email) throws Exception {
private suffices

2017-01-31 20:14 UTC, ebeutler requested changes
Just two empty lines to remove.

2017-01-31 20:14 UTC, ebeutler commented on component/src/main/java/com/celements/blog/plugin/NewsletterReceivers.java
> +
please remove empty line

2017-01-31 20:14 UTC, ebeutler commented on component/src/main/java/com/celements/blog/plugin/NewsletterReceivers.java
> +
please remove empty line

2017-02-02 15:34 UTC, msladek approved these changes

2017-02-02 15:50 UTC, ebeutler approved these changes

2017-02-07 14:14 UTC, merged