BlogWebSearchPackage
celements/celements-blog pull request #24
Opened 2017-06-30 19:12 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-395

first review: https://github.com/celements/celements-search/pull/4

2017-07-23 15:07 UTC, fpichler requested changes

2017-07-23 15:07 UTC, fpichler commented on component/src/main/java/com/celements/blog/search/BlogWebSearchPackage.java
> +      QueryRestrictionGroup grp = searchService.createRestrictionGroup(Type.OR);
you need to additionally restrict to the "lang"-object. Multilinguality in the Blog is solved with an additional article-object per language. Thus on search you must restrict on the specific language.

2017-07-28 15:44 UTC, fpichler requested changes

2017-07-28 15:44 UTC, fpichler commented on component/src/main/java/com/celements/blog/search/BlogWebSearchPackage.java
> +  public IQueryRestriction getQueryRestriction(XWikiDocument cfgDoc, String searchTerm) {
Please add some unit tests covering the logic of getQueryRestriction.

2017-07-31 09:18 UTC, ebeutler approved these changes

2017-07-31 09:18 UTC, ebeutler commented on component/src/test/java/com/celements/blog/search/BlogWebSearchPackageTest.java
> +  BlogWebSearchPackage webSearchPackage;
please make private

2017-08-04 19:47 UTC, fpichler approved these changes

2017-08-04 21:37 UTC, merged